/* ------------------------------------------------------------------ */
/* Binary file storage for uploaded documents.                         */
/*                                                                     */
/* The database only keeps metadata (student_files); the bytes live in */
/* a FileStore: a local directory (default data/files), an S3-          */
/* compatible bucket (e.g. Hetzner Object Storage) via Bun's built-in  */
/* S3 client, or memory (demo mode and tests).                         */
/* ------------------------------------------------------------------ */

import { mkdir, rm } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";
import { S3Client } from "bun";

export interface FileStore {
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  delete(key: string): Promise<void>;
}

/* Keys are generated by the server (e.g. students/12/<uuid>), never taken
   from user input — this check is a second line of defence against path
   traversal in the disk store. */
const KEY_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]*(\/[A-Za-z0-9][A-Za-z0-9._-]*)*$/;

export function assertValidKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.split("/").some((part) => part === "..")) {
    throw new Error(`Invalid storage key: ${key}`);
  }
}

export class MemoryFileStore implements FileStore {
  readonly files = new Map<string, { bytes: Uint8Array; contentType: string }>();

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    assertValidKey(key);
    this.files.set(key, { bytes: new Uint8Array(bytes), contentType });
  }

  async get(key: string): Promise<Uint8Array | null> {
    return this.files.get(key)?.bytes ?? null;
  }

  async delete(key: string): Promise<void> {
    this.files.delete(key);
  }
}

export class DiskFileStore implements FileStore {
  readonly dir: string;

  constructor(dir = "data/files") {
    this.dir = resolve(dir);
  }

  private path(key: string): string {
    assertValidKey(key);
    const full = resolve(this.dir, ...key.split("/"));
    if (!full.startsWith(this.dir + sep)) throw new Error(`Invalid storage key: ${key}`);
    return full;
  }

  async put(key: string, bytes: Uint8Array, _contentType: string): Promise<void> {
    const path = this.path(key);
    await mkdir(dirname(path), { recursive: true });
    await Bun.write(path, bytes);
  }

  async get(key: string): Promise<Uint8Array | null> {
    const file = Bun.file(this.path(key));
    if (!(await file.exists())) return null;
    return new Uint8Array(await file.arrayBuffer());
  }

  async delete(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}

/** A view of another store below a key prefix, e.g. "<slug>/" — one
 *  school's documents in multi-tenant mode, outside a request context
 *  (backup jobs, restore). */
export class PrefixedFileStore implements FileStore {
  constructor(
    readonly base: FileStore,
    readonly prefix: string,
  ) {}
  put(key: string, bytes: Uint8Array, contentType: string) {
    assertValidKey(key);
    return this.base.put(`${this.prefix}${key}`, bytes, contentType);
  }
  get(key: string) {
    assertValidKey(key);
    return this.base.get(`${this.prefix}${key}`);
  }
  delete(key: string) {
    assertValidKey(key);
    return this.base.delete(`${this.prefix}${key}`);
  }
}

/* The subset of Bun's S3Client the stores use — lets tests inject a fake
   without any network access. */
export type S3ClientLike = {
  write(
    key: string,
    data: Uint8Array | Blob,
    options?: { type?: string },
  ): Promise<number>;
  file(key: string): { exists(): Promise<boolean>; arrayBuffer(): Promise<ArrayBuffer> };
  delete(key: string): Promise<void>;
  list(input?: { prefix?: string; startAfter?: string; maxKeys?: number }): Promise<{
    contents?: { key: string; size?: number; lastModified?: string }[];
    isTruncated?: boolean;
  }>;
};

export class S3FileStore implements FileStore {
  constructor(
    private readonly client: S3ClientLike,
    /** Prepended to every key, e.g. "openfs/files/". */
    private readonly prefix = "files/",
  ) {}

  private objectKey(key: string): string {
    assertValidKey(key);
    return `${this.prefix}${key}`;
  }

  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    await this.client.write(this.objectKey(key), bytes, { type: contentType });
  }

  async get(key: string): Promise<Uint8Array | null> {
    const file = this.client.file(this.objectKey(key));
    if (!(await file.exists())) return null;
    return new Uint8Array(await file.arrayBuffer());
  }

  async delete(key: string): Promise<void> {
    await this.client.delete(this.objectKey(key));
  }
}

export type S3Config = {
  endpoint: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  region?: string;
  /** Normalized: empty or ending in "/". */
  prefix: string;
};

type Env = Record<string, string | undefined>;

/** S3 settings from S3_ENDPOINT / S3_BUCKET / S3_ACCESS_KEY_ID /
 *  S3_SECRET_ACCESS_KEY (+ optional S3_REGION, S3_PREFIX); null unless
 *  all required variables are set. */
export function s3ConfigFromEnv(env: Env = process.env): S3Config | null {
  const endpoint = env.S3_ENDPOINT?.trim();
  const bucket = env.S3_BUCKET?.trim();
  const accessKeyId = env.S3_ACCESS_KEY_ID?.trim();
  const secretAccessKey = env.S3_SECRET_ACCESS_KEY?.trim();
  if (!endpoint || !bucket || !accessKeyId || !secretAccessKey) return null;
  const rawPrefix = (env.S3_PREFIX ?? "").trim().replace(/^\/+/, "");
  return {
    endpoint,
    bucket,
    accessKeyId,
    secretAccessKey,
    region: env.S3_REGION?.trim() || undefined,
    prefix: rawPrefix && !rawPrefix.endsWith("/") ? `${rawPrefix}/` : rawPrefix,
  };
}

export function createS3Client(config: S3Config): S3ClientLike {
  return new S3Client({
    endpoint: config.endpoint,
    bucket: config.bucket,
    accessKeyId: config.accessKeyId,
    secretAccessKey: config.secretAccessKey,
    region: config.region,
  }) as unknown as S3ClientLike;
}

export function createFileStoreFromEnv(options: { demoMode: boolean; env?: Env }): {
  store: FileStore;
  kind: "memory" | "s3" | "disk";
} {
  if (options.demoMode) return { store: new MemoryFileStore(), kind: "memory" };
  const env = options.env ?? process.env;
  const s3 = s3ConfigFromEnv(env);
  if (s3) {
    return {
      store: new S3FileStore(createS3Client(s3), `${s3.prefix}files/`),
      kind: "s3",
    };
  }
  return {
    store: new DiskFileStore(env.FILE_STORE_DIR?.trim() || join("data", "files")),
    kind: "disk",
  };
}
